### ISSUE TITLE
Why not Mojo::SQLite?

### ISSUE THREAD

**Issue by kberov** [Grinnz/perldoc-browser#8]
If this application was using Mojo::SQLite it would be much more portable.
Would you advise how this can be achieved? May be via a plugin?
I saw PerldocBrowser::Plugin::PerldocSearchPg but could not figure out from first glance what needs to be done to have PerldocBrowser::Plugin::PerldocSearchSQLite. Are there too many Pg specific features used, etc?
Thanks!

**Comment by Grinnz** [comment]
The application can be deployed without a search module by specifying the no_search config option (may change this), this means that Mojo::Pg is not needed. SQLite full-text search support does not have stopword support by default which makes it non-ideal. However I am in the process of making the search more modular as you can see from the SearchPg plugin, as I might be switching to Elasticsearch because postgres full-text search also has several issues. An SQLite search plugin would be reasonable but would just not skip stopwords.

**Comment by kberov** [comment]
Thanks. I wish I had some free time for implementing PerldocBrowser::Plugin::PerldocSearchSQLite.
Anyone?

**Comment by Grinnz** [comment]
There is now a SQLite backend, which can be selected by setting search_backend => 'sqlite'.

**Comment by kberov** [comment]
These are really good news! Thanks Dan!
